version: '3'

services:

  frontend:
    build: ./frontend
    ports:
      - "4343:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "4242:5000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
    ports:
      - "4141:3306"
